version: '3.7'
services:
  proxy:
    image: "beancodede/theredshirts-proxy:latest"
    build: ./nginx-data
    container_name: infra-proxy
    ports:
    - "1203:1203"
    environment:
    - NGINX_PORT=1203
    depends_on:
      lobby:
        condition: service_started
      message:
        condition: service_started
      authi:
        condition: service_started
    links:
      - lobby:lobby
      - message:message
      - authi:authi
  postgres:
    image: postgres:latest
    container_name: infra-postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
  pgadmin:
    container_name: monitoring-pgadmin4
    image: dpage/pgadmin4
    command:
      - --loglevel warning
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.de
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  authi:
    image: "beancodede/authi:latest"
    container_name: theredshirts-authi
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
      - LOG_LEVEL=debug
    volumes: 
      - ./authi-data/token:/token
      - ./authi-data/authi.conf:/authi.conf
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
  message:
    image: "beancodede/theredshirts-message:latest"
    container_name: theredshirts-message
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
      - LOG_LEVEL=warn
      - JAEGER_SERVICE_NAME=theredshirts-message
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - LOBBY_USER=00000000-0000-0000-0000-000000000001
    depends_on:
      postgres:
        condition: service_healthy
      authi:
        condition: service_started
    links:
      - postgres:postgres
      - authi:authi
  lobby:
    image: "beancodede/theredshirts-lobby:latest"
    container_name: theredshirts-lobby
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
      - LOG_LEVEL=debug
      - JAEGER_SERVICE_NAME=theredshirts-lobby
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - LOBBY_USER=00000000-0000-0000-0000-000000000001
    depends_on:
      postgres:
        condition: service_healthy
      message:
        condition: service_started
      authi:
        condition: service_started
    links:
      - postgres:postgres
      - message:message
      - authi:authi
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: monitoring-jeager
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=warn