{
 "title": "Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Create message id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "message_request_duration_seconds_sum{method=\"POST\", url=\"/message/:lobbyId/msg\", host=\"theredshirts-message:1203\"} / message_request_duration_seconds_count{method=\"POST\", url=\"/message/:lobbyId/msg\", host=\"theredshirts-message:1203\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "message_request_duration_seconds_sum{method=\"PUT\", url=\"/message/:lobbyId/msg/:messageId\", host=\"theredshirts-message:1203\"} / message_request_duration_seconds_count{method=\"PUT\", url=\"/message/:lobbyId/msg/:messageId\", host=\"theredshirts-message:1203\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "message_request_duration_seconds_sum{method=\"GET\", url=\"/message/:lobbyId/msg/:number\"} / message_request_duration_seconds_count{method=\"GET\", url=\"/message/:lobbyId/msg/:number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"GET\", url=\"/server/ping\"} / lobby_request_duration_seconds_count{method=\"GET\", url=\"/server/ping\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Player", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Create player",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"PUT\", url=\"/player/:playerId\"} / lobby_request_duration_seconds_count{method=\"PUT\", url=\"/player/:playerId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update player",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"PATCH\", url=\"/player/:playerId\"} / lobby_request_duration_seconds_count{method=\"PATCH\", url=\"/player/:playerId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update player refresh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"PATCH\", url=\"/player/:playerId/last-refresh\"} / lobby_request_duration_seconds_count{method=\"PATCH\", url=\"/player/:playerId/last-refresh\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get player",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"GET\", url=\"/player/:playerId\"} / lobby_request_duration_seconds_count{method=\"GET\", url=\"/player/:playerId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete player",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"DELETE\", url=\"/player/:playerId\"} / lobby_request_duration_seconds_count{method=\"DELETE\", url=\"/player/:playerId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lobby", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Create lobby id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"POST\", url=\"/lobby\"} / lobby_request_duration_seconds_count{method=\"POST\", url=\"/lobby\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create lobby",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"GET\", url=\"/lobby/:lobbyId\"} / lobby_request_duration_seconds_count{method=\"GET\", url=\"/lobby/:lobbyId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update lobby",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"PATCH\", url=\"/lobby/:lobbyId\"} / lobby_request_duration_seconds_count{method=\"PATCH\", url=\"/lobby/:lobbyId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update lobby status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"PATCH\", url=\"/lobby/:lobbyId/status\"} / lobby_request_duration_seconds_count{method=\"PATCH\", url=\"/lobby/:lobbyId/status\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete lobby",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"DELETE\", url=\"/lobby/:lobbyId\"} / lobby_request_duration_seconds_count{method=\"DELETE\", url=\"/lobby/:lobbyId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get lobby",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"GET\", url=\"/lobby/:lobbyId\"} / lobby_request_duration_seconds_count{method=\"GET\", url=\"/lobby/:lobbyId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get all lobbies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lobby_request_duration_seconds_sum{method=\"GET\", url=\"/lobby\"} / lobby_request_duration_seconds_count{method=\"GET\", url=\"/lobby\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}